### PR TITLE
Implement flashdeltaall and nodeid prefixing

### PR DESCRIPTION
**Pull request by gtfierro**
Forgot to include flashdelta all in the last PR. Also adds nodeid prefixing for `sload tailall -p`, which goes from this:

```
[DN00DW22]  
[DN00DW22]  SERIAL NUMBER 0x304d
[DN00DW22]  IPAddress - Setting global address: 2001:470:83ae:2:212:6d02::304d
[DN00DW22]  error? 1 length 5
[DN00DW22]  Loading prefix from flash attribute 2: :212:6d02:0:304d
[DN00DW22]  IPAddress - Setting global address: :212:6d02:0:304d
[DN00DW22]  Booting kernel 4.0.7.0 (848c5d3281462fc9b1b407cdf9ac0cd02465fc1f)
[DN00DW22]  Starting init RPL
[DN00DW22]  not root, starting periodic
[DN00DW1I]  SERIAL NUMBER 0x310b
[DN00DW22]  Boo
[DN00DW1I]  IPAddress - Setting global address: 2001:470:83ae:2:212:6d02::310b
[DJ00DH9S]  SERIAL NUMBER 0x4013
[DN00DW1I]  error? 1 length 5
[DN00DW1I]  Loading prefix from flash attribute 2: :212:6d02:0:310b
```

to this

```
[304d]  
[304d]  SERIAL NUMBER 0x304d
[304d]  IPAddress - Setting global address: 2001:470:83ae:2:212:6d02::304d
[304d]  error? 1 length 5
[304d]  Loading prefix from flash attribute 2: :212:6d02:0:304d
[304d]  IPAddress - Setting global address: :212:6d02:0:304d
[304d]  Booting kernel 4.0.7.0 (848c5d3281462fc9b1b407cdf9ac0cd02465fc1f)
[304d]  Starting init RPL
[304d]  not root, starting periodic
[310b]  SERIAL NUMBER 0x310b
[304d]  Boo
[310b]  IPAddress - Setting global address: 2001:470:83ae:2:212:6d02::310b
[4013]  SERIAL NUMBER 0x4013
[310b]  error? 1 length 5
[4013]  IPAddress - Setting global address: 2001:470:83ae:2:212:6d02::4013
[310b]  Loading prefix from flash attribute 2: :212:6d02:0:310b
[310b]  IPAddress - Setting global address: :212:6d02:0:310b
[4013]  error? 1 length 5
[4013]  Booting kernel 4.0.7.0 (848c5d3281462fc9b1b407cdf9ac0cd02465fc1f)
[304d]  ting payload 4.0:asking for time
[310b]  Booting kernel 4.0.7.0 (848c5d3281462fc9b1b407cdf9ac0cd02465fc1f)
[310b]  Starting init RPL
[4013]  Starting init RPL
[4013]  not root, starting periodic
```

### CODE REVIEW

**Comment by gtfierro** [comment]
Added a quick fix. Need this to be merged to do the rpi border router

**Comment by gtfierro** [comment]
Added quick per-device caching for userland to avoid the long waits on subsequent runs

**Comment by immesys** [comment]
I'll merge this in. Do you want me to make a new pip release as well?

**Comment by gtfierro** [comment]
Another pip release would be good, thanks

**Pull request merged**
